# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28f8561722269e0fc3495a29fa89c4c209c4d63b560ca0f265955226cb24ac4794c0fb3af29636a992d81e7ffca262eaf08f25c571ded4081362d0c547654b57

test:
  secret_key_base: 2d24472aa2c0c2511db296454d48069bf76f34904bd376d372a7178777ca7f1829e982afd4666306ecd36d6fa83702c5c812b037dc11f237c7ba0dfef6a679e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
